# Generated by Django 3.0.7 on 2020-06-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200614_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payu_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
